Added more precise failure logic

diff --git a/.github/workflows/Test.yml b/.github/workflows/Test.yml
--- a/.github/workflows/Test.yml
+++ b/.github/workflows/Test.yml
@@ -46,18 +46,22 @@ jobs:
           poetry install --no-interaction --with dev
       - name: Enforce code formatting
         id: black
+        continue-on-error: true
         run: poetry run black .
       - name: Enforce code style
         id: pylint
+        continue-on-error: true
         run: poetry run pylint $(git ls-files './metabase_tools/*.py')
       - name: Enforce type hinting
         id: mypy
+        continue-on-error: true
         run: poetry run mypy --strict $(git ls-files './metabase_tools/*.py')
       - name: Setup Metabase
         id: setup
         run: poetry run python ./tests/setup_metabase.py
       - name: Test with pytest
         id: pytest
+        continue-on-error: true
         run: poetry run pytest --cov=metabase_tools --cov-report=xml --cov-report=html --cov-fail-under=95
       - name: Upload coverage to Codecov
         id: codecov
@@ -85,8 +89,14 @@ jobs:
           path: docs/build/html/
       - name: Upload log artifacts
         id: log_upload
-        if: success() || failure()
         uses: actions/upload-artifact@v3
         with:
           name: logs
           path: temp/
+      - name: Determine failure or success
+        id: resolve
+        run: |
+          if [[ ${{ steps.black.outcome }} == "failure" ]]; then echo 'black failure'; exit 1; fi
+          if [[ ${{ steps.pylint.outcome }} == "failure" ]]; then echo 'pylint failure'; exit 1; fi
+          if [[ ${{ steps.mypy.outcome }} == "failure" ]]; then echo 'mypy failure'; exit 1; fi
+          if [[ ${{ steps.pytest.outcome }} == "failure" ]]; then echo 'pytest failure'; exit 1; fi
